spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/oswc

server:
  port: 8080

app:
  jwt:
    # 32자 이상 랜덤 문자열로 교체!
    secret: "replace-with-a-long-random-secret-32+chars"
    access-exp-min: 30
    refresh-exp-days: 14

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: info
    org.springframework.security: DEBUG
