spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/oswc
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

server:
  port: 8080

app:
  jwt:
    # 32바이트(문자 32자 이상) 랜덤 문자열로 바꾸세요
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32CHARS_MIN"
    access-exp-min: 30
    refresh-exp-days: 14
  upload:
    dir: uploads  # 아바타 저장 루트

logging:
  level:
    org.springframework.security: DEBUG
